$('document').ready(function(){
  $('.clickable').click(function(){
    $('.hidden').click(function(){
      $('img').show();
    });
    $('.showing').click(function(){
      $('img').hide();
    });
  });
});
